### ISSUE TITLE
taxid_trees missing from custom databases in docker images

### ISSUE THREAD

**Issue by akinkhabwala** [ParkinsonLab/MetaPro_tutorial#1]
Hi!

I'm afraid I'm getting stuck at the Genome Assembly (GA) step, because I can't find the taxid_trees files. I've tried using both the v3.0.1 and "latest" docker images, but neither of them seem to have the taxid_trees files in the /pipeline/custom_databases folder. I can't find any information on where to download these files, so I think I've hit a wall. Any help you can provide would be greatly appreciated!

Cheers,
Anika

**Comment by billylaw8** [comment]
Taxid trees isn't part of this tutorial.
